name: Levelling
main: com.tribescommunity.levelling.Levelling
version: 1.2.1
author: theguynextdoor
softdepend: [Vault, TagAPI]
commands:
  levels:
    description: stats command
    usage: /<command>
    aliases: [level, l]
  levelling:
    description: main command
    usage: /<command>
  class:
    description: class command
    usage: /<command>
    aliases: [trade]
  leveladmin:
    description: leveladmin command
    usage: /<command>
    aliases: [la]
  party:
    description: party command
    usage: /<command>
  partychat:
    description: party chat command
    usage: /<command>
    aliases: [p, pc]
  ptp:
    description: part tp command
    usage: /<command> <player>
  mining:
    description: mining commmand
    usage: /<command>
  archaeology:
    description: archaeology commmand
    usage: /<command>
  archery:
    description: archery commmand
    usage: /<command>
  swords:
    description: swords command
    usage: /<command>
  unarmed:
    description: unarmed command
    usage: /<command>
  farming:
    description: farming command
    usage: /<command>
  woodcutting:
    description: woodcutting command
    usage: /<command>
  enchanting:
    description: enchanting command
    usage: /<command>
  lockpicking:
    description: lockpicking command
    usage: /<command>
  pickpocketing:
    description: pickpocketing command
    usage: /<command>
  repair:
    description: repair command
    usage: /<command>
    aliases: [smithing]
  cooking:
    description: cooking command
    usage: /<command>
  building:
    description: building comnd
    usage: /<command>
  goldpanning:
    description: goldpanning command
    usage: /<command>
  adminchat:
    description: admin chat command
    usage: /<command> <message>
    aliases: [a, ac]
  modchat:
    description: mod chat command
    usage: /<command> <message>
    aliases: [m, mc]
  vipchat:
    description: vip chat command
    usage: /<command> <message>
    aliases: [v, vc]
  achievements:
    description: achievement command
    usage: /<command>
    aliases: [achieve, ach]
  title:
    description: title command
    usage: /<command> set <title>
  titles:
    description: titles command
    usage: /<command>