package com.tribescommunity.levelling.achievements;

public enum Tracking {
	BLOCKS_TRAVELLED,
	MESSAGES_SENT,
	HOSTILE_MOBS_KILLED,
	ANIMALS_KILLED,
	PLAYERS_KILLED,
	TOTAL_SKILL_LEVELS_GAINED,
	DEATHS,
	LOGINS,
	BLOCKS_PLACED,
	BLOCKS_BROKEN,
	TELEPORTS,
	ITEMS_CRAFTED,
	ITEMS_SMELTED,
	ARROWS_SHOT,
	SNOWBALLS_THROWN,
	KILLSTREAK;
}